Repository SU-SWS/ood-giving-campaign, pull requests merged in 2024-10, with the labels that each got.

#352 Release: v3.0.0
  .adr-dir
  README.md
  app/(editor)/editor/page.tsx
  app/(storyblok)/[[...slug]]/not-found.tsx
  app/(storyblok)/[[...slug]]/page.tsx
  app/not-found.tsx
  app/sitemap.ts
  components/Cta/CtaLink.tsx
  components/Cta/CtaNextLink.tsx
  components/Storyblok/SbStoryFilterPage/SbStoryFilterPage.tsx
  components/Storyblok/SbStoryListNav/SbStoryListNav.tsx
  docs/decisions/0002-split-content-directories-and-slug-handling.md
  docs/decisions/0003-active-environment-is-the-context-environment-variable.md
  docs/environment-variables.md
  netlify.toml
  netlify/functions/storyblok-background.mts
  next.config.js
  package-lock.json
  package.json
  utilities/data/getStoryData.ts
  utilities/data/getStoryList.ts
  utilities/getActiveEnv.ts
  utilities/getPageMetadata.ts
  utilities/getSlugPrefix.ts
  utilities/sbStripSlugUrl.ts
Labels: major

#354 Release: v3.0.1
  netlify/functions/storyblok-background.mts
Labels: patch, retro

#356 Release: v3.0.2
  app/(storyblok)/[[...slug]]/not-found.tsx
  app/(storyblok)/[[...slug]]/page.tsx
  app/not-found.tsx
  app/sitemap.ts
  utilities/data/getStoryData.ts
  utilities/data/getStoryList.ts
Labels: patch

#361 Release: v3.2.0
  app/(editor)/editor/page.tsx
  app/(storyblok)/[[...slug]]/page.tsx
  next.config.mjs
  utilities/data/getStoryData.ts
  utilities/data/getStoryblokRedirects.mjs
Labels: minor

#366 Release/v3.2.1
  app/sitemap.ts
  components/AnnotatedImage/ImageHotspot.styles.ts
  components/AnnotatedImage/ImageHotspot.tsx
  components/Cta/CtaLink.tsx
  components/Cta/CtaNextLink.tsx
  components/EventBanner/EventBanner.tsx
  components/FeaturedStories/FeatureMasonry.tsx
  components/MomentPoster/MomentPoster.tsx
  components/Storyblok/SbEventBanner.tsx
  components/Storyblok/SbFeatureMasonry.tsx
  components/Storyblok/SbHomepageThemeSection/SbHomepageThemeSection.tsx
  components/Storyblok/SbSection/SbSection.tsx
  components/Storyblok/SbStoryCard.tsx
  components/Storyblok/SbStoryListNav/SbStoryListNav.tsx
  components/Storyblok/SbText.tsx
  docs/decisions/0004-font-loading.md
  package-lock.json
  package.json
  utilities/data/getStoryblokRedirects.mjs
  utilities/getPageMetadata.ts
  utilities/sbStripSlugUrl.ts
Labels: patch
